import { Provider } from './carrier.types';

export const providers: Provider[] = [
  {
    id: 1,
    name: 'Rahul Kumar',
    kind: 'Individual',
    avatar: 'RK',
    rating: 4.8,
    jobs: 124,
    capacity: 100,
    distance: 1.2,
    available: true,
    price: 450,
    teamSize: 1,
    equipment: ['Hand trolley', 'Rope set'],
    serviceArea: 'Andheri, Mumbai',
    reviews: ['Fast and careful with our office move.', 'Very professional and punctual.'],
  },
  {
    id: 2,
    name: 'Amit Sharma',
    kind: 'Individual',
    avatar: 'AS',
    rating: 4.6,
    jobs: 89,
    capacity: 250,
    distance: 2.4,
    available: true,
    price: 650,
    teamSize: 1,
    equipment: ['Hydraulic trolley', 'Protective wraps'],
    serviceArea: 'Powai, Mumbai',
    reviews: ['Handled a heavy machine without a problem.'],
  },
  {
    id: 3,
    name: 'Sameer Logistics',
    kind: 'Team',
    avatar: 'SL',
    rating: 4.9,
    jobs: 312,
    capacity: 1000,
    distance: 3.8,
    available: true,
    price: 1450,
    teamSize: 4,
    equipment: ['Mini crane', 'Straps', 'Loading ramp'],
    serviceArea: 'Thane and Mumbai',
    reviews: ['Excellent team for complex loads.', 'Great communication from start to finish.'],
  },
  {
    id: 4,
    name: 'QuickLift Team',
    kind: 'Team',
    avatar: 'QL',
    rating: 4.5,
    jobs: 201,
    capacity: 500,
    distance: 5.1,
    available: false,
    price: 950,
    teamSize: 3,
    equipment: ['Loading ramp', 'Dolly'],
    serviceArea: 'Bandra, Mumbai',
    reviews: ['Friendly team and fair pricing.'],
  },
  {
    id: 5,
    name: 'Mumbai Load Assist',
    kind: 'Team',
    avatar: 'ML',
    rating: 4.7,
    jobs: 176,
    capacity: 750,
    distance: 6.4,
    available: true,
    price: 1100,
    teamSize: 3,
    equipment: ['Forklift', 'Cargo straps'],
    serviceArea: 'Navi Mumbai',
    reviews: ['Reliable for long-distance delivery.'],
  },
];
